### ISSUE TITLE
Fixed Frame [map] does not exist

### ISSUE THREAD

**Issue by zainmehdi** [wh200720041/FLOAM_ssl#1]
Hi, thanks for this awesome package. When I try to run your launch file I am getting the above mentioned error and no mapping. Should I publish a static transform from base link to L515_link ?
Thanks

**Comment by wh200720041** [comment]
Hi @zainmehdi 

May I know which launch you use?

Han

**Comment by zainmehdi** [comment]
Thanks for the reply. I used floam_ssl_L515.launch.

**Comment by zainmehdi** [comment]
Sorry for the inconvenience I got it running. There was some issue in the topic mapping from my end.
Thanks alot.

**Comment by zainmehdi** [comment]
Hi @wh200720041 , I was wondering if your approach could be used to calculating odometry as a hand held device. I tried it and because the motion was not constrained to 2D plane the node crashed often. Can you please provide some insight ?

**Comment by wh200720041** [comment]
Hi @zainmehdi 
The hand held device is supposed to work on 3D space right?

If you want to use on 2d plane, I think just force the output of roll, pitch, and z to be zero will do

**Comment by zainmehdi** [comment]
Thanks for the response. I meant that I want to use it as a handheld device. I tried it with L515 and the pose kept jumping alot. My aim is just the odometry no mapping. I tried different available odometry algorithms and thought yours might work well. It does when placed on a mobile robot but when the user is walking it seems to break down.

**Comment by wh200720041** [comment]
Hi @zainmehdi 

I think if use for handheld use the angular speed can be high sometimes. Since the FoV of L515 is small, it may lose track on the feature points and cause localization failure.  Perhaps you can use gimbal like DJI osmo.

Han
